use_frameworks!

platform :ios, '16.0'

target 'AeroAccess_Example' do
  pod 'AeroAccess'
  
  pod 'Alamofire'
  pod 'MistSDKDR'
  pod 'RealmSwift', '~>10'

  target 'AeroAccess_Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer|
#    installer.generated_projects.each do |project|
#          project.targets.each do |target|
#              target.build_configurations.each do |config|
#                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
#               end
#          end
#   end
    
    xcode_base_version = `xcodebuild -version | grep 'Xcode' | awk '{print $2}' | cut -d . -f 1`

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        # For xcode 15+ only
        if config.base_configuration_reference && Integer(xcode_base_version) >= 15
          xcconfig_path = config.base_configuration_reference.real_path
          xcconfig = File.read(xcconfig_path)
          xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
          File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }
        end
      end
    end
    
end
